import React, { createContext, useContext, useState, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Lang = 'fr' | 'en' | 'es' | 'ar';
type LangCtx = { lang: Lang; setLang: (l: Lang) => void; t: (key: string) => string };

const T: Record<Lang, Record<string, string>> = {
  fr: {
    hello: 'Bonjour', good_afternoon: 'Bon après-midi', good_evening: 'Bonsoir',
    home: 'Accueil', courses: 'Cours', looks: 'Looks', profile: 'Profil',
    weather_loading: 'Chargement météo...', humidity: 'Humidité',
    ready_session: 'Prête pour votre session ?', select_products: 'Sélectionnez vos produits et lancez le studio',
    access_studio: 'Accéder au Studio', quick_access: 'Accès rapide',
    go_premium: 'Passer Premium', my_sub: 'Mon abonnement', premium_active: 'Premium actif', unlock_all: 'Débloquer tout',
    skin_analysis: 'Analyse peau', ai_diagnosis: 'Diagnostic IA', sub_required: 'Abonnement requis',
    sub_required_msg: "L'analyse de peau est réservée aux abonnés Premium.",
    login: 'Se connecter', register: 'Créer mon compte', email: 'Email', password: 'Mot de passe',
    name: 'Prénom', city: 'Ville', no_account: 'Pas encore de compte ?', create_account: 'Créer un compte',
    has_account: 'Déjà un compte ?', connect: 'Connectez-vous à votre compte', create_beauty: 'Créer votre compte beauté',
    edit: 'Modifier', save: 'Sauvegarder', administrator: 'Administrateur', premium_member: 'Membre Premium', free_member: 'Membre gratuit',
    full_access: 'Accès complet à toutes les fonctionnalités ARIA',
    upgrade_text: 'Passez à Premium pour l\'analyse faciale et les cours avancés', discover: 'Découvrir',
    admin_dashboard: 'Administration', admin_stats: 'Dashboard & statistiques',
    contact_support: 'Contacter l\'assistance', contact_issue: 'En cas de problème de compte',
    logout: 'Se déconnecter', new_password: 'Nouveau mot de passe', leave_empty: 'Laisser vide si inchangé',
    my_looks: 'Mes Looks', no_looks: 'Aucun look sauvegardé', save_makeup: 'Sauvegardez votre sélection maquillage pour la réutiliser chaque jour',
    create_look: 'Créer mon look', new_look: 'Nouveau Look', look_name: 'Nom du look',
    products_shades: 'Produits & Teintes', notes: 'Notes (optionnel)', products_selected: 'produit(s) sélectionné(s)',
    save_btn: 'Sauvegarder', use_look: 'Utiliser ce look', delete: 'Supprimer',
    tutorials_available: 'tutoriels disponibles', see_steps: 'Voir les étapes', steps: 'Étapes',
    launch_studio: 'Lancer dans le Studio', premium_content: 'Contenu Premium',
    premium_tutorial_msg: "Ce tutoriel est réservé aux abonnés Premium.",
    selection: 'Sélection Maquillage', choose_products: 'Choisissez vos produits et teintes',
    order_title: 'Ordre d\'application', order_sub: 'Réorganisez vos produits dans l\'ordre souhaité', confirm_launch: 'Lancer le Studio',
    sub_title: 'Abonnement', aria_premium: 'ARIA PREMIUM', per_month: '/mois', unlock_potential: 'Débloquez tout le potentiel d\'ARIA',
    subscribe: 'S\'abonner', checking_payment: 'Vérification du paiement...',
    feat_skin: 'Analyse de peau IA avancée', feat_looks: 'Looks sauvegardés illimités',
    feat_tutorials: 'Tous les tutoriels débloqués', feat_routines: 'Routines soins personnalisées',
    contact_title: 'Contact', need_help: 'Besoin d\'aide ?',
    contact_email_info: 'Notre équipe vous répondra à aria.administration@gmail.com',
    from: 'De', subject: 'Sujet', message: 'Message', send: 'Envoyer',
    skin_title: 'Analyse de peau', skin_diagnosis: 'Diagnostic IA de votre peau',
    skin_instructions: 'Prenez un selfie en lumière naturelle.\nNotre IA analysera votre peau et vous recommandera des produits adaptés.',
    take_photo: 'Prendre une photo', analyzing: 'Analyse en cours...', ai_studying: 'Notre IA étudie votre peau',
    skin_type: 'Peau', observations: 'Observations', recommended: 'Produits recommandés',
    routine: 'Routine conseillée', morning: 'Matin', evening: 'Soir', retry: 'Refaire une analyse',
    chat_placeholder: 'Posez votre question beauté...', chat_assistant: 'Assistante Beauté IA',
    studio: 'Studio ARIA', camera_required: 'Accès caméra requis', camera_desc: 'ARIA a besoin de votre caméra pour le studio maquillage',
    allow_camera: 'Autoriser la caméra', back: 'Retour', ai_guide: 'Guidage IA Face Mesh — bientôt disponible',
    language: 'Langue',
  },
  en: {
    hello: 'Hello', good_afternoon: 'Good afternoon', good_evening: 'Good evening',
    home: 'Home', courses: 'Courses', looks: 'Looks', profile: 'Profile',
    weather_loading: 'Loading weather...', humidity: 'Humidity',
    ready_session: 'Ready for your session?', select_products: 'Select your products and launch the studio',
    access_studio: 'Access Studio', quick_access: 'Quick access',
    go_premium: 'Go Premium', my_sub: 'My subscription', premium_active: 'Premium active', unlock_all: 'Unlock all',
    skin_analysis: 'Skin analysis', ai_diagnosis: 'AI Diagnosis', sub_required: 'Subscription required',
    sub_required_msg: 'Skin analysis is reserved for Premium subscribers.',
    login: 'Log in', register: 'Create account', email: 'Email', password: 'Password',
    name: 'First name', city: 'City', no_account: 'No account yet?', create_account: 'Create account',
    has_account: 'Already have an account?', connect: 'Connect to your account', create_beauty: 'Create your beauty account',
    edit: 'Edit', save: 'Save', administrator: 'Administrator', premium_member: 'Premium member', free_member: 'Free member',
    full_access: 'Full access to all ARIA features',
    upgrade_text: 'Upgrade to Premium for facial analysis and advanced courses', discover: 'Discover',
    admin_dashboard: 'Administration', admin_stats: 'Dashboard & statistics',
    contact_support: 'Contact support', contact_issue: 'Account issues',
    logout: 'Log out', new_password: 'New password', leave_empty: 'Leave empty if unchanged',
    my_looks: 'My Looks', no_looks: 'No saved looks', save_makeup: 'Save your makeup selection to reuse it every day',
    create_look: 'Create my look', new_look: 'New Look', look_name: 'Look name',
    products_shades: 'Products & Shades', notes: 'Notes (optional)', products_selected: 'product(s) selected',
    save_btn: 'Save', use_look: 'Use this look', delete: 'Delete',
    tutorials_available: 'tutorials available', see_steps: 'See steps', steps: 'Steps',
    launch_studio: 'Launch in Studio', premium_content: 'Premium Content',
    premium_tutorial_msg: 'This tutorial is reserved for Premium subscribers.',
    selection: 'Makeup Selection', choose_products: 'Choose your products and shades',
    order_title: 'Application Order', order_sub: 'Reorder your products as you wish', confirm_launch: 'Launch Studio',
    sub_title: 'Subscription', aria_premium: 'ARIA PREMIUM', per_month: '/month', unlock_potential: 'Unlock ARIA\'s full potential',
    subscribe: 'Subscribe', checking_payment: 'Checking payment...',
    feat_skin: 'Advanced AI skin analysis', feat_looks: 'Unlimited saved looks',
    feat_tutorials: 'All tutorials unlocked', feat_routines: 'Personalized skincare routines',
    contact_title: 'Contact', need_help: 'Need help?',
    contact_email_info: 'Our team will respond at aria.administration@gmail.com',
    from: 'From', subject: 'Subject', message: 'Message', send: 'Send',
    skin_title: 'Skin Analysis', skin_diagnosis: 'AI Skin Diagnosis',
    skin_instructions: 'Take a selfie in natural light.\nOur AI will analyze your skin and recommend adapted products.',
    take_photo: 'Take a photo', analyzing: 'Analyzing...', ai_studying: 'Our AI is studying your skin',
    skin_type: 'Skin', observations: 'Observations', recommended: 'Recommended products',
    routine: 'Recommended routine', morning: 'Morning', evening: 'Evening', retry: 'Redo analysis',
    chat_placeholder: 'Ask your beauty question...', chat_assistant: 'AI Beauty Assistant',
    studio: 'ARIA Studio', camera_required: 'Camera access required', camera_desc: 'ARIA needs your camera for the makeup studio',
    allow_camera: 'Allow camera', back: 'Back', ai_guide: 'AI Face Mesh guidance — coming soon',
    language: 'Language',
  },
  es: {
    hello: 'Hola', good_afternoon: 'Buenas tardes', good_evening: 'Buenas noches',
    home: 'Inicio', courses: 'Cursos', looks: 'Looks', profile: 'Perfil',
    weather_loading: 'Cargando clima...', humidity: 'Humedad',
    ready_session: '¿Lista para tu sesión?', select_products: 'Selecciona tus productos y lanza el estudio',
    access_studio: 'Acceder al Estudio', quick_access: 'Acceso rápido',
    go_premium: 'Hazte Premium', my_sub: 'Mi suscripción', premium_active: 'Premium activo', unlock_all: 'Desbloquear todo',
    skin_analysis: 'Análisis de piel', ai_diagnosis: 'Diagnóstico IA', sub_required: 'Suscripción requerida',
    sub_required_msg: 'El análisis de piel está reservado para suscriptores Premium.',
    login: 'Iniciar sesión', register: 'Crear cuenta', email: 'Correo', password: 'Contraseña',
    name: 'Nombre', city: 'Ciudad', no_account: '¿No tienes cuenta?', create_account: 'Crear cuenta',
    has_account: '¿Ya tienes cuenta?', connect: 'Conéctate a tu cuenta', create_beauty: 'Crea tu cuenta de belleza',
    edit: 'Editar', save: 'Guardar', administrator: 'Administrador', premium_member: 'Miembro Premium', free_member: 'Miembro gratuito',
    full_access: 'Acceso completo a todas las funciones de ARIA',
    upgrade_text: 'Pasa a Premium para análisis facial y cursos avanzados', discover: 'Descubrir',
    admin_dashboard: 'Administración', admin_stats: 'Panel y estadísticas',
    contact_support: 'Contactar soporte', contact_issue: 'Problemas de cuenta',
    logout: 'Cerrar sesión', new_password: 'Nueva contraseña', leave_empty: 'Dejar vacío si no cambia',
    my_looks: 'Mis Looks', no_looks: 'Sin looks guardados', save_makeup: 'Guarda tu selección de maquillaje para reutilizarla cada día',
    create_look: 'Crear mi look', new_look: 'Nuevo Look', look_name: 'Nombre del look',
    products_shades: 'Productos y tonos', notes: 'Notas (opcional)', products_selected: 'producto(s) seleccionado(s)',
    save_btn: 'Guardar', use_look: 'Usar este look', delete: 'Eliminar',
    tutorials_available: 'tutoriales disponibles', see_steps: 'Ver pasos', steps: 'Pasos',
    launch_studio: 'Lanzar en Estudio', premium_content: 'Contenido Premium',
    premium_tutorial_msg: 'Este tutorial está reservado para suscriptores Premium.',
    selection: 'Selección de Maquillaje', choose_products: 'Elige tus productos y tonos',
    order_title: 'Orden de aplicación', order_sub: 'Reordena tus productos como desees', confirm_launch: 'Lanzar Estudio',
    sub_title: 'Suscripción', aria_premium: 'ARIA PREMIUM', per_month: '/mes', unlock_potential: 'Desbloquea todo el potencial de ARIA',
    subscribe: 'Suscribirse', checking_payment: 'Verificando pago...',
    feat_skin: 'Análisis de piel IA avanzado', feat_looks: 'Looks guardados ilimitados',
    feat_tutorials: 'Todos los tutoriales desbloqueados', feat_routines: 'Rutinas de cuidado personalizadas',
    contact_title: 'Contacto', need_help: '¿Necesitas ayuda?',
    contact_email_info: 'Nuestro equipo responderá en aria.administration@gmail.com',
    from: 'De', subject: 'Asunto', message: 'Mensaje', send: 'Enviar',
    skin_title: 'Análisis de piel', skin_diagnosis: 'Diagnóstico IA de tu piel',
    skin_instructions: 'Toma un selfie con luz natural.\nNuestra IA analizará tu piel y recomendará productos.',
    take_photo: 'Tomar foto', analyzing: 'Analizando...', ai_studying: 'Nuestra IA estudia tu piel',
    skin_type: 'Piel', observations: 'Observaciones', recommended: 'Productos recomendados',
    routine: 'Rutina recomendada', morning: 'Mañana', evening: 'Noche', retry: 'Rehacer análisis',
    chat_placeholder: 'Haz tu pregunta de belleza...', chat_assistant: 'Asistente de Belleza IA',
    studio: 'Estudio ARIA', camera_required: 'Acceso a cámara requerido', camera_desc: 'ARIA necesita tu cámara para el estudio',
    allow_camera: 'Permitir cámara', back: 'Volver', ai_guide: 'Guía IA Face Mesh — próximamente',
    language: 'Idioma',
  },
  ar: {
    hello: 'مرحبا', good_afternoon: 'مساء الخير', good_evening: 'مساء الخير',
    home: 'الرئيسية', courses: 'الدورات', looks: 'الإطلالات', profile: 'الملف',
    weather_loading: 'جاري تحميل الطقس...', humidity: 'الرطوبة',
    ready_session: 'مستعدة لجلستك؟', select_products: 'اختاري منتجاتك وابدئي الاستوديو',
    access_studio: 'دخول الاستوديو', quick_access: 'وصول سريع',
    go_premium: 'الترقية للبريميوم', my_sub: 'اشتراكي', premium_active: 'بريميوم نشط', unlock_all: 'فتح الكل',
    skin_analysis: 'تحليل البشرة', ai_diagnosis: 'تشخيص ذكاء اصطناعي', sub_required: 'يتطلب اشتراك',
    sub_required_msg: 'تحليل البشرة مخصص لمشتركي البريميوم',
    login: 'تسجيل الدخول', register: 'إنشاء حساب', email: 'البريد', password: 'كلمة المرور',
    name: 'الاسم', city: 'المدينة', no_account: 'ليس لديك حساب؟', create_account: 'إنشاء حساب',
    has_account: 'لديك حساب؟', connect: 'تسجيل الدخول', create_beauty: 'أنشئي حساب الجمال',
    edit: 'تعديل', save: 'حفظ', administrator: 'مدير', premium_member: 'عضو بريميوم', free_member: 'عضو مجاني',
    full_access: 'وصول كامل لجميع ميزات ARIA',
    upgrade_text: 'ترقي للبريميوم لتحليل الوجه والدورات المتقدمة', discover: 'اكتشفي',
    admin_dashboard: 'الإدارة', admin_stats: 'لوحة التحكم',
    contact_support: 'تواصلي مع الدعم', contact_issue: 'مشاكل الحساب',
    logout: 'تسجيل الخروج', new_password: 'كلمة مرور جديدة', leave_empty: 'اتركي فارغا إذا لم يتغير',
    my_looks: 'إطلالاتي', no_looks: 'لا توجد إطلالات', save_makeup: 'احفظي مكياجك لإعادة استخدامه يوميا',
    create_look: 'إنشاء إطلالة', new_look: 'إطلالة جديدة', look_name: 'اسم الإطلالة',
    products_shades: 'المنتجات والألوان', notes: 'ملاحظات', products_selected: 'منتج(ات) محددة',
    save_btn: 'حفظ', use_look: 'استخدام هذه الإطلالة', delete: 'حذف',
    tutorials_available: 'دورات متاحة', see_steps: 'عرض الخطوات', steps: 'الخطوات',
    launch_studio: 'تشغيل في الاستوديو', premium_content: 'محتوى بريميوم',
    premium_tutorial_msg: 'هذه الدورة مخصصة لمشتركي البريميوم',
    selection: 'اختيار المكياج', choose_products: 'اختاري منتجاتك وألوانك',
    order_title: 'ترتيب التطبيق', order_sub: 'رتبي منتجاتك حسب رغبتك', confirm_launch: 'تشغيل الاستوديو',
    sub_title: 'الاشتراك', aria_premium: 'ARIA بريميوم', per_month: '/شهر', unlock_potential: 'افتحي كل إمكانيات ARIA',
    subscribe: 'اشتراك', checking_payment: 'التحقق من الدفع...',
    feat_skin: 'تحليل بشرة متقدم', feat_looks: 'إطلالات غير محدودة',
    feat_tutorials: 'جميع الدورات مفتوحة', feat_routines: 'روتين عناية مخصص',
    contact_title: 'التواصل', need_help: 'تحتاجين مساعدة؟',
    contact_email_info: 'فريقنا سيرد على aria.administration@gmail.com',
    from: 'من', subject: 'الموضوع', message: 'الرسالة', send: 'إرسال',
    skin_title: 'تحليل البشرة', skin_diagnosis: 'تشخيص بشرتك بالذكاء الاصطناعي',
    skin_instructions: 'التقطي صورة سيلفي بضوء طبيعي.\nسيحلل ذكاؤنا الاصطناعي بشرتك ويوصي بمنتجات مناسبة.',
    take_photo: 'التقاط صورة', analyzing: 'جاري التحليل...', ai_studying: 'ذكاؤنا يدرس بشرتك',
    skin_type: 'بشرة', observations: 'الملاحظات', recommended: 'منتجات موصى بها',
    routine: 'الروتين المقترح', morning: 'صباح', evening: 'مساء', retry: 'إعادة التحليل',
    chat_placeholder: 'اسألي سؤال جمالك...', chat_assistant: 'مساعدة الجمال',
    studio: 'استوديو ARIA', camera_required: 'يتطلب الوصول للكاميرا', camera_desc: 'ARIA تحتاج كاميرتك للاستوديو',
    allow_camera: 'السماح بالكاميرا', back: 'رجوع', ai_guide: 'توجيه ذكاء اصطناعي — قريبا',
    language: 'اللغة',
  },
};

const LANG_LABELS: Record<Lang, string> = { fr: 'FR', en: 'EN', es: 'ES', ar: 'AR' };
const LANG_NAMES: Record<Lang, string> = { fr: 'Français', en: 'English', es: 'Español', ar: 'العربية' };

const LanguageContext = createContext<LangCtx>({ lang: 'fr', setLang: () => {}, t: (k) => k });

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr');

  React.useEffect(() => {
    AsyncStorage.getItem('aria_lang').then(v => { if (v && (v === 'fr' || v === 'en' || v === 'es' || v === 'ar')) setLangState(v as Lang); });
  }, []);

  const setLang = (l: Lang) => { setLangState(l); AsyncStorage.setItem('aria_lang', l); };
  const t = (key: string) => T[lang]?.[key] || T['fr']?.[key] || key;

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
export { LANG_LABELS, LANG_NAMES, T };
export type { Lang };
